from typing import TypedDict, List, Optional, Dict, Any, Annotated
import operator
from pydantic import BaseModel, Field

# --- Pydantic Schemas for Structured JSON Output ---

class BugSummary(BaseModel):
    symptoms: str = Field(description="Description of the bug symptoms and what is failing.")
    scope: str = Field(description="Scope of the issue (e.g., localized to a component, system-wide).")
    severity: str = Field(description="Severity of the issue (e.g., Critical, High, Medium, Low).")

class PatchPlanSchema(BaseModel):
    files_impacted: List[str] = Field(description="List of mock files or modules impacted by the proposed patch.")
    approach: str = Field(description="Detailed description of the proposed coding approach to fix the bug.")
    risks: str = Field(description="Potential risks or side-effects associated with this approach.")

class ValidationPlan(BaseModel):
    tests_to_add: List[str] = Field(description="Suggested unit/integration tests to add to validate the fix.")
    regression_checks: List[str] = Field(description="Regression checks to ensure no existing functionality breaks.")

class BugReportFinalOutput(BaseModel):
    bug_summary: BugSummary
    evidence: List[str] = Field(description="Log line excerpts and stack traces used as evidence.")
    repro_steps: List[str] = Field(description="Exact steps taken by the agent to reproduce the bug.")
    repro_artifact_path: str = Field(description="File path to the generated minimal reproduction script.")
    root_cause_hypothesis: str = Field(description="The primary hypothesis for the root cause of the bug.")
    confidence: float = Field(description="Confidence level in the hypothesis (0.0 to 1.0).")
    patch_plan: PatchPlanSchema
    validation_plan: ValidationPlan
    open_questions: List[str] = Field(description="Missing information or open questions requiring human input.")

# --- LangGraph State Definition ---

class DebuggerState(TypedDict):
    """The central state dictionary passed between all agents in the LangGraph."""
    
    # Inputs
    bug_report: str
    logs: str
    
    # Agent Accumulated Evidence
    triage_summary: Optional[str]
    extracted_evidence: Optional[List[str]]
    
    # Reproduction Sandbox Data
    repro_script: Optional[str]         # The python code generated by the agent
    repro_results: Optional[str]        # Stdout/Stderr from running the script
    repro_success: bool                 # Did the script successfully crash/fail in the expected way?
    repro_attempts: int                 # Number of times the repro script was attempted
    max_repro_attempts: int             # Hard limit to prevent infinite loops
    
    # Fix Planning
    root_cause_proposal: Optional[str]
    patch_plan_raw: Optional[str]
    
    # Code Review
    reviewer_notes: Optional[str]       # Feedback from the critic agent
    is_approved: bool                   # Did the reviewer approve the fix plan and repro?
    
    # Final Output
    final_structured_output: Optional[dict]
    
    # Meta
    agent_traces: Annotated[List[Dict[str, Any]], operator.add] # Log of all agent actions for the UI
